# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:26:42+00:00



import argparse
import json
import os
from typing import *
from typing import Optional

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import BaseSecurity, UnsuportedSecurityStub
from fastapi import Path, Query

from models import (
    Account,
    Alt,
    Attachment,
    AttachmentsListResponse,
    Contact,
    ContactsListResponse,
    Location,
    LocationsListResponse,
    OrderBy,
    Setting,
    Subscription,
    SubscriptionsListResponse,
    TimelineItem,
    TimelineListResponse,
)

app = MCPProxy(
    contact={'name': 'Google', 'url': 'https://google.com'},
    description='Interacts with Glass users via the timeline.',
    license={
        'name': 'Creative Commons Attribution 3.0',
        'url': 'http://creativecommons.org/licenses/by/3.0/',
    },
    termsOfService='https://developers.google.com/terms/',
    title='Google Mirror',
    version='v1',
    servers=[{'url': 'https://www.googleapis.com/mirror/v1'}],
)


@app.post(
    '/accounts/{userToken}/{accountType}/{accountName}',
    description=""" Inserts a new account for a user """,
    tags=['user_account_management'],
)
def mirror_accounts_insert(
    user_token: str = Path(..., alias='userToken'),
    account_type: str = Path(..., alias='accountType'),
    account_name: str = Path(..., alias='accountName'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Account = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/contacts',
    description=""" Retrieves a list of contacts for the authenticated user. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_list(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/contacts',
    description=""" Inserts a new contact. """,
    tags=['user_contact_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_insert(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Contact = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/contacts/{id}',
    description=""" Deletes a contact. """,
    tags=['user_account_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_delete(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/contacts/{id}',
    description=""" Gets a single contact by ID. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_get(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/contacts/{id}',
    description=""" Updates a contact in place. This method supports patch semantics. """,
    tags=['user_contact_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_patch(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Contact = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/contacts/{id}',
    description=""" Updates a contact in place. """,
    tags=['user_contact_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_contacts_update(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Contact = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/locations',
    description=""" Retrieves a list of locations for the user. """,
    tags=['user_account_management', 'user_settings_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_locations_list(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/locations/{id}',
    description=""" Gets a single location by ID. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_locations_get(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/settings/{id}',
    description=""" Gets a single setting by ID. """,
    tags=['user_settings_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_settings_get(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/subscriptions',
    description=""" Retrieves a list of subscriptions for the authenticated user and service. """,
    tags=['user_account_management', 'user_settings_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_subscriptions_list(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/subscriptions',
    description=""" Creates a new subscription. """,
    tags=['user_subscription_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_subscriptions_insert(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Subscription = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/subscriptions/{id}',
    description=""" Deletes a subscription. """,
    tags=['user_account_management', 'user_settings_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_subscriptions_delete(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/subscriptions/{id}',
    description=""" Updates an existing subscription in place. """,
    tags=['user_subscription_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_subscriptions_update(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: Subscription = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/timeline',
    description=""" Retrieves a list of timeline items for the authenticated user. """,
    tags=['user_timeline_management', 'timeline_attachment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_list(
    bundle_id: Optional[str] = Query(None, alias='bundleId'),
    include_deleted: Optional[bool] = Query(None, alias='includeDeleted'),
    max_results: Optional[int] = Query(None, alias='maxResults'),
    order_by: Optional[OrderBy] = Query(None, alias='orderBy'),
    page_token: Optional[str] = Query(None, alias='pageToken'),
    pinned_only: Optional[bool] = Query(None, alias='pinnedOnly'),
    source_item_id: Optional[str] = Query(None, alias='sourceItemId'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/timeline',
    description=""" Inserts a new item into the timeline. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_insert(
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/timeline/{id}',
    description=""" Deletes a timeline item. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_delete(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/timeline/{id}',
    description=""" Gets a single timeline item by ID. """,
    tags=['user_account_management', 'user_settings_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_get(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.patch(
    '/timeline/{id}',
    description=""" Updates a timeline item in place. This method supports patch semantics. """,
    tags=['user_timeline_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_patch(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
    body: TimelineItem = None,
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.put(
    '/timeline/{id}',
    description=""" Updates a timeline item in place. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_update(
    id: str,
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/timeline/{itemId}/attachments',
    description=""" Returns a list of attachments for a timeline item. """,
    tags=[
        'user_account_management',
        'user_contact_management',
        'user_location_management',
        'user_settings_management',
        'user_subscription_management',
        'user_timeline_management',
        'timeline_attachment_management',
    ],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_attachments_list(
    item_id: str = Path(..., alias='itemId'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/timeline/{itemId}/attachments',
    description=""" Adds a new attachment to a timeline item. """,
    tags=['user_timeline_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_attachments_insert(
    item_id: str = Path(..., alias='itemId'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.delete(
    '/timeline/{itemId}/attachments/{attachmentId}',
    description=""" Deletes an attachment from a timeline item. """,
    tags=['timeline_attachment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_attachments_delete(
    item_id: str = Path(..., alias='itemId'),
    attachment_id: str = Path(..., alias='attachmentId'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.get(
    '/timeline/{itemId}/attachments/{attachmentId}',
    description=""" Retrieves an attachment on a timeline item by item ID and attachment ID. """,
    tags=['timeline_attachment_management'],
    security=[
        UnsuportedSecurityStub(name="None"),
        UnsuportedSecurityStub(name="None"),
    ],
)
def mirror_timeline_attachments_get(
    item_id: str = Path(..., alias='itemId'),
    attachment_id: str = Path(..., alias='attachmentId'),
    alt: Optional[Alt] = 'json',
    fields: Optional[str] = None,
    key: Optional[str] = None,
    oauth_token: Optional[str] = None,
    pretty_print: Optional[bool] = Query(True, alias='prettyPrint'),
    quota_user: Optional[str] = Query(None, alias='quotaUser'),
    user_ip: Optional[str] = Query(None, alias='userIp'),
):
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
