# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:26:42+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class Attachment(BaseModel):
    contentType: Optional[str] = Field(
        None, description='The MIME type of the attachment.'
    )
    contentUrl: Optional[str] = Field(None, description='The URL for the content.')
    id: Optional[str] = Field(None, description='The ID of the attachment.')
    isProcessingContent: Optional[bool] = Field(
        None,
        description='Indicates that the contentUrl is not available because the attachment content is still being processed. If the caller wishes to retrieve the content, it should try again later.',
    )


class AttachmentsListResponse(BaseModel):
    items: Optional[List[Attachment]] = Field(
        None, description='The list of attachments.'
    )
    kind: Optional[str] = Field(
        'mirror#attachmentsList',
        description='The type of resource. This is always mirror#attachmentsList.',
    )


class AuthToken(BaseModel):
    authToken: Optional[str] = None
    type: Optional[str] = None


class Command(BaseModel):
    type: Optional[str] = Field(
        None,
        description='The type of operation this command corresponds to. Allowed values are:  \n- TAKE_A_NOTE - Shares a timeline item with the transcription of user speech from the "Take a note" voice menu command.  \n- POST_AN_UPDATE - Shares a timeline item with the transcription of user speech from the "Post an update" voice menu command.',
    )


class Contact(BaseModel):
    acceptCommands: Optional[List[Command]] = Field(
        None,
        description='A list of voice menu commands that a contact can handle. Glass shows up to three contacts for each voice menu command. If there are more than that, the three contacts with the highest priority are shown for that particular command.',
    )
    acceptTypes: Optional[List[str]] = Field(
        None,
        description='A list of MIME types that a contact supports. The contact will be shown to the user if any of its acceptTypes matches any of the types of the attachments on the item. If no acceptTypes are given, the contact will be shown for all items.',
    )
    displayName: Optional[str] = Field(
        None, description='The name to display for this contact.'
    )
    id: Optional[str] = Field(
        None,
        description='An ID for this contact. This is generated by the application and is treated as an opaque token.',
    )
    imageUrls: Optional[List[str]] = Field(
        None,
        description='Set of image URLs to display for a contact. Most contacts will have a single image, but a "group" contact may include up to 8 image URLs and they will be resized and cropped into a mosaic on the client.',
    )
    kind: Optional[str] = Field(
        'mirror#contact',
        description='The type of resource. This is always mirror#contact.',
    )
    phoneNumber: Optional[str] = Field(
        None,
        description='Primary phone number for the contact. This can be a fully-qualified number, with country calling code and area code, or a local number.',
    )
    priority: Optional[int] = Field(
        None,
        description='Priority for the contact to determine ordering in a list of contacts. Contacts with higher priorities will be shown before ones with lower priorities.',
    )
    sharingFeatures: Optional[List[str]] = Field(
        None,
        description='A list of sharing features that a contact can handle. Allowed values are:  \n- ADD_CAPTION',
    )
    source: Optional[str] = Field(
        None,
        description='The ID of the application that created this contact. This is populated by the API',
    )
    speakableName: Optional[str] = Field(
        None,
        description="Name of this contact as it should be pronounced. If this contact's name must be spoken as part of a voice disambiguation menu, this name is used as the expected pronunciation. This is useful for contact names with unpronounceable characters or whose display spelling is otherwise not phonetic.",
    )
    type: Optional[str] = Field(
        None,
        description='The type for this contact. This is used for sorting in UIs. Allowed values are:  \n- INDIVIDUAL - Represents a single person. This is the default. \n- GROUP - Represents more than a single person.',
    )


class ContactsListResponse(BaseModel):
    items: Optional[List[Contact]] = Field(None, description='Contact list.')
    kind: Optional[str] = Field(
        'mirror#contacts',
        description='The type of resource. This is always mirror#contacts.',
    )


class Location(BaseModel):
    accuracy: Optional[float] = Field(
        None, description='The accuracy of the location fix in meters.'
    )
    address: Optional[str] = Field(
        None, description='The full address of the location.'
    )
    displayName: Optional[str] = Field(
        None,
        description='The name to be displayed. This may be a business name or a user-defined place, such as "Home".',
    )
    id: Optional[str] = Field(None, description='The ID of the location.')
    kind: Optional[str] = Field(
        'mirror#location',
        description='The type of resource. This is always mirror#location.',
    )
    latitude: Optional[float] = Field(None, description='The latitude, in degrees.')
    longitude: Optional[float] = Field(None, description='The longitude, in degrees.')
    timestamp: Optional[datetime] = Field(
        None,
        description='The time at which this location was captured, formatted according to RFC 3339.',
    )


class LocationsListResponse(BaseModel):
    items: Optional[List[Location]] = Field(None, description='The list of locations.')
    kind: Optional[str] = Field(
        'mirror#locationsList',
        description='The type of resource. This is always mirror#locationsList.',
    )


class MenuValue(BaseModel):
    displayName: Optional[str] = Field(
        None,
        description='The name to display for the menu item. If you specify this property for a built-in menu item, the default contextual voice command for that menu item is not shown.',
    )
    iconUrl: Optional[str] = Field(
        None, description='URL of an icon to display with the menu item.'
    )
    state: Optional[str] = Field(
        None,
        description='The state that this value applies to. Allowed values are:  \n- DEFAULT - Default value shown when displayed in the menuItems list. \n- PENDING - Value shown when the menuItem has been selected by the user but can still be cancelled. \n- CONFIRMED - Value shown when the menuItem has been selected by the user and can no longer be cancelled.',
    )


class NotificationConfig(BaseModel):
    deliveryTime: Optional[datetime] = Field(
        None, description='The time at which the notification should be delivered.'
    )
    level: Optional[str] = Field(
        None,
        description='Describes how important the notification is. Allowed values are:  \n- DEFAULT - Notifications of default importance. A chime will be played to alert users.',
    )


class Setting(BaseModel):
    id: Optional[str] = Field(
        None,
        description="The setting's ID. The following IDs are valid:  \n- locale - The key to the user’s language/locale (BCP 47 identifier) that Glassware should use to render localized content.  \n- timezone - The key to the user’s current time zone region as defined in the tz database. Example: America/Los_Angeles.",
    )
    kind: Optional[str] = Field(
        'mirror#setting',
        description='The type of resource. This is always mirror#setting.',
    )
    value: Optional[str] = Field(None, description='The setting value, as a string.')


class UserAction(BaseModel):
    payload: Optional[str] = Field(
        None,
        description='An optional payload for the action.\n\nFor actions of type CUSTOM, this is the ID of the custom menu item that was selected.',
    )
    type: Optional[str] = Field(
        None,
        description='The type of action. The value of this can be:  \n- SHARE - the user shared an item. \n- REPLY - the user replied to an item. \n- REPLY_ALL - the user replied to all recipients of an item. \n- CUSTOM - the user selected a custom menu item on the timeline item. \n- DELETE - the user deleted the item. \n- PIN - the user pinned the item. \n- UNPIN - the user unpinned the item. \n- LAUNCH - the user initiated a voice command.  In the future, additional types may be added. UserActions with unrecognized types should be ignored.',
    )


class UserData(BaseModel):
    key: Optional[str] = None
    value: Optional[str] = None


class Alt(Enum):
    json = 'json'


class OrderBy(Enum):
    displayTime = 'displayTime'
    writeTime = 'writeTime'


class Account(BaseModel):
    authTokens: Optional[List[AuthToken]] = None
    features: Optional[List[str]] = None
    password: Optional[str] = None
    userData: Optional[List[UserData]] = None


class MenuItem(BaseModel):
    action: Optional[str] = Field(
        None,
        description="Controls the behavior when the user picks the menu option. Allowed values are:  \n- CUSTOM - Custom action set by the service. When the user selects this menuItem, the API triggers a notification to your callbackUrl with the userActions.type set to CUSTOM and the userActions.payload set to the ID of this menu item. This is the default value. \n- Built-in actions:  \n- REPLY - Initiate a reply to the timeline item using the voice recording UI. The creator attribute must be set in the timeline item for this menu to be available. \n- REPLY_ALL - Same behavior as REPLY. The original timeline item's recipients will be added to the reply item. \n- DELETE - Delete the timeline item. \n- SHARE - Share the timeline item with the available contacts. \n- READ_ALOUD - Read the timeline item's speakableText aloud; if this field is not set, read the text field; if none of those fields are set, this menu item is ignored. \n- GET_MEDIA_INPUT - Allow users to provide media payloads to Glassware from a menu item (currently, only transcribed text from voice input is supported). Subscribe to notifications when users invoke this menu item to receive the timeline item ID. Retrieve the media from the timeline item in the payload property. \n- VOICE_CALL - Initiate a phone call using the timeline item's creator.phoneNumber attribute as recipient. \n- NAVIGATE - Navigate to the timeline item's location. \n- TOGGLE_PINNED - Toggle the isPinned state of the timeline item. \n- OPEN_URI - Open the payload of the menu item in the browser. \n- PLAY_VIDEO - Open the payload of the menu item in the Glass video player. \n- SEND_MESSAGE - Initiate sending a message to the timeline item's creator:  \n- If the creator.phoneNumber is set and Glass is connected to an Android phone, the message is an SMS. \n- Otherwise, if the creator.email is set, the message is an email.",
    )
    contextual_command: Optional[str] = Field(
        None,
        description="The ContextualMenus.Command associated with this MenuItem (e.g. READ_ALOUD). The voice label for this command will be displayed in the voice menu and the touch label will be displayed in the touch menu. Note that the default menu value's display name will be overriden if you specify this property. Values that do not correspond to a ContextualMenus.Command name will be ignored.",
    )
    id: Optional[str] = Field(
        None,
        description='The ID for this menu item. This is generated by the application and is treated as an opaque token.',
    )
    payload: Optional[str] = Field(
        None,
        description="A generic payload whose meaning changes depending on this MenuItem's action.  \n- When the action is OPEN_URI, the payload is the URL of the website to view. \n- When the action is PLAY_VIDEO, the payload is the streaming URL of the video \n- When the action is GET_MEDIA_INPUT, the payload is the text transcription of a user's speech input",
    )
    removeWhenSelected: Optional[bool] = Field(
        None,
        description='If set to true on a CUSTOM menu item, that item will be removed from the menu after it is selected.',
    )
    values: Optional[List[MenuValue]] = Field(
        None,
        description='For CUSTOM items, a list of values controlling the appearance of the menu item in each of its states. A value for the DEFAULT state must be provided. If the PENDING or CONFIRMED states are missing, they will not be shown.',
    )


class Notification(BaseModel):
    collection: Optional[str] = Field(
        None, description='The collection that generated the notification.'
    )
    itemId: Optional[str] = Field(
        None, description='The ID of the item that generated the notification.'
    )
    operation: Optional[str] = Field(
        None, description='The type of operation that generated the notification.'
    )
    userActions: Optional[List[UserAction]] = Field(
        None,
        description='A list of actions taken by the user that triggered the notification.',
    )
    userToken: Optional[str] = Field(
        None,
        description='The user token provided by the service when it subscribed for notifications.',
    )
    verifyToken: Optional[str] = Field(
        None,
        description='The secret verify token provided by the service when it subscribed for notifications.',
    )


class Subscription(BaseModel):
    callbackUrl: Optional[str] = Field(
        None,
        description='The URL where notifications should be delivered (must start with https://).',
    )
    collection: Optional[str] = Field(
        None,
        description='The collection to subscribe to. Allowed values are:  \n- timeline - Changes in the timeline including insertion, deletion, and updates. \n- locations - Location updates. \n- settings - Settings updates.',
    )
    id: Optional[str] = Field(None, description='The ID of the subscription.')
    kind: Optional[str] = Field(
        'mirror#subscription',
        description='The type of resource. This is always mirror#subscription.',
    )
    notification: Optional[Notification] = Field(
        None,
        description='Container object for notifications. This is not populated in the Subscription resource.',
    )
    operation: Optional[List[str]] = Field(
        None,
        description='A list of operations that should be subscribed to. An empty list indicates that all operations on the collection should be subscribed to. Allowed values are:  \n- UPDATE - The item has been updated. \n- INSERT - A new item has been inserted. \n- DELETE - The item has been deleted. \n- MENU_ACTION - A custom menu item has been triggered by the user.',
    )
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this subscription was last modified, formatted according to RFC 3339.',
    )
    userToken: Optional[str] = Field(
        None,
        description='An opaque token sent to the subscriber in notifications so that it can determine the ID of the user.',
    )
    verifyToken: Optional[str] = Field(
        None,
        description='A secret token sent to the subscriber in notifications so that it can verify that the notification was generated by Google.',
    )


class SubscriptionsListResponse(BaseModel):
    items: Optional[List[Subscription]] = Field(
        None, description='The list of subscriptions.'
    )
    kind: Optional[str] = Field(
        'mirror#subscriptionsList',
        description='The type of resource. This is always mirror#subscriptionsList.',
    )


class TimelineItem(BaseModel):
    attachments: Optional[List[Attachment]] = Field(
        None,
        description='A list of media attachments associated with this item. As a convenience, you can refer to attachments in your HTML payloads with the attachment or cid scheme. For example:  \n- attachment: <img src="attachment:attachment_index"> where attachment_index is the 0-based index of this array. \n- cid: <img src="cid:attachment_id"> where attachment_id is the ID of the attachment.',
    )
    bundleId: Optional[str] = Field(
        None,
        description='The bundle ID for this item. Services can specify a bundleId to group many items together. They appear under a single top-level item on the device.',
    )
    canonicalUrl: Optional[str] = Field(
        None,
        description='A canonical URL pointing to the canonical/high quality version of the data represented by the timeline item.',
    )
    created: Optional[datetime] = Field(
        None,
        description='The time at which this item was created, formatted according to RFC 3339.',
    )
    creator: Optional[Contact] = Field(
        None, description='The user or group that created this item.'
    )
    displayTime: Optional[datetime] = Field(
        None,
        description="The time that should be displayed when this item is viewed in the timeline, formatted according to RFC 3339. This user's timeline is sorted chronologically on display time, so this will also determine where the item is displayed in the timeline. If not set by the service, the display time defaults to the updated time.",
    )
    etag: Optional[str] = Field(None, description='ETag for this item.')
    html: Optional[str] = Field(
        None,
        description="HTML content for this item. If both text and html are provided for an item, the html will be rendered in the timeline.\nAllowed HTML elements - You can use these elements in your timeline cards.\n \n- Headers: h1, h2, h3, h4, h5, h6 \n- Images: img \n- Lists: li, ol, ul \n- HTML5 semantics: article, aside, details, figure, figcaption, footer, header, nav, section, summary, time \n- Structural: blockquote, br, div, hr, p, span \n- Style: b, big, center, em, i, u, s, small, strike, strong, style, sub, sup \n- Tables: table, tbody, td, tfoot, th, thead, tr  \nBlocked HTML elements: These elements and their contents are removed from HTML payloads.\n \n- Document headers: head, title \n- Embeds: audio, embed, object, source, video \n- Frames: frame, frameset \n- Scripting: applet, script  \nOther elements: Any elements that aren't listed are removed, but their contents are preserved.",
    )
    id: Optional[str] = Field(
        None,
        description="The ID of the timeline item. This is unique within a user's timeline.",
    )
    inReplyTo: Optional[str] = Field(
        None,
        description='If this item was generated as a reply to another item, this field will be set to the ID of the item being replied to. This can be used to attach a reply to the appropriate conversation or post.',
    )
    isBundleCover: Optional[bool] = Field(
        None,
        description='Whether this item is a bundle cover.\n\nIf an item is marked as a bundle cover, it will be the entry point to the bundle of items that have the same bundleId as that item. It will be shown only on the main timeline — not within the opened bundle.\n\nOn the main timeline, items that are shown are:  \n- Items that have isBundleCover set to true  \n- Items that do not have a bundleId  In a bundle sub-timeline, items that are shown are:  \n- Items that have the bundleId in question AND isBundleCover set to false',
    )
    isDeleted: Optional[bool] = Field(
        None,
        description='When true, indicates this item is deleted, and only the ID property is set.',
    )
    isPinned: Optional[bool] = Field(
        None,
        description='When true, indicates this item is pinned, which means it\'s grouped alongside "active" items like navigation and hangouts, on the opposite side of the home screen from historical (non-pinned) timeline items. You can allow the user to toggle the value of this property with the TOGGLE_PINNED built-in menu item.',
    )
    kind: Optional[str] = Field(
        'mirror#timelineItem',
        description='The type of resource. This is always mirror#timelineItem.',
    )
    location: Optional[Location] = Field(
        None, description='The geographic location associated with this item.'
    )
    menuItems: Optional[List[MenuItem]] = Field(
        None,
        description='A list of menu items that will be presented to the user when this item is selected in the timeline.',
    )
    notification: Optional[NotificationConfig] = Field(
        None,
        description='Controls how notifications for this item are presented on the device. If this is missing, no notification will be generated.',
    )
    pinScore: Optional[int] = Field(
        None,
        description='For pinned items, this determines the order in which the item is displayed in the timeline, with a higher score appearing closer to the clock. Note: setting this field is currently not supported.',
    )
    recipients: Optional[List[Contact]] = Field(
        None,
        description='A list of users or groups that this item has been shared with.',
    )
    selfLink: Optional[str] = Field(
        None, description='A URL that can be used to retrieve this item.'
    )
    sourceItemId: Optional[str] = Field(
        None,
        description='Opaque string you can use to map a timeline item to data in your own service.',
    )
    speakableText: Optional[str] = Field(
        None,
        description='The speakable version of the content of this item. Along with the READ_ALOUD menu item, use this field to provide text that would be clearer when read aloud, or to provide extended information to what is displayed visually on Glass.\n\nGlassware should also specify the speakableType field, which will be spoken before this text in cases where the additional context is useful, for example when the user requests that the item be read aloud following a notification.',
    )
    speakableType: Optional[str] = Field(
        None,
        description='A speakable description of the type of this item. This will be announced to the user prior to reading the content of the item in cases where the additional context is useful, for example when the user requests that the item be read aloud following a notification.\n\nThis should be a short, simple noun phrase such as "Email", "Text message", or "Daily Planet News Update".\n\nGlassware are encouraged to populate this field for every timeline item, even if the item does not contain speakableText or text so that the user can learn the type of the item without looking at the screen.',
    )
    text: Optional[str] = Field(None, description='Text content of this item.')
    title: Optional[str] = Field(None, description='The title of this item.')
    updated: Optional[datetime] = Field(
        None,
        description='The time at which this item was last modified, formatted according to RFC 3339.',
    )


class TimelineListResponse(BaseModel):
    items: Optional[List[TimelineItem]] = Field(
        None, description='Items in the timeline.'
    )
    kind: Optional[str] = Field(
        'mirror#timeline',
        description='The type of resource. This is always mirror#timeline.',
    )
    nextPageToken: Optional[str] = Field(
        None,
        description='The next page token. Provide this as the pageToken parameter in the request to retrieve the next page of results.',
    )
